### ISSUE TITLE
Control Over Position of the Popover Needed

### ISSUE THREAD

**Issue by OrKoN** [ember-vcl/popover#1]
E.g. currently it's always below and to the right of the original position.

But it should check if there is enough space in that direction and re-position itself if there is no space.

**Comment by vanthome** [comment]
Yes, @st-agnes please apply the logic that we discussed for the date-picker, actually I thought it is already implemented on the popover level...

**Comment by OrKoN** [comment]
@vanthome @st-agnes this logic may become a mixin on its own, for example `ember-vcl-self-positioning-support`

**Comment by vanthome** [comment]
Yes, `ember-vcl-autopos-support` I would propose.

**Comment by st-agnes** [comment]
Hi, what we have discussed originally is that the dropdown-menu should support the self-positioning behavior, for which it is already implemented. I will create a mixin for this and integrate it into the popover as well.

**Comment by vanthome** [comment]
@st-agnes ok bu I think we discussed that dropdown menu should also use the popover and thus this functionality should actually only reside in the popover. So I think a mixin is not even required.

**Comment by piotrpalek** [comment]
resolved by adding tether support to the popover in v0.3.1
